config/routes.rb
ChessCampP2::Application.routes.draw do

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search
  
  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :camps
  resources :camp_instructors
  resources :instructors 
  resources :curriculums
  
  # You can have the root of your site routed with 'root'
  root 'home#index'

end

app/models/curriculum.rb
class Curriculum < ActiveRecord::Base
  # relationships
  has_many :camps

  # validations
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  ratings_array = [0] + (100..3000).to_a
  validates :min_rating, numericality: { only_integer: true }, inclusion: { in: ratings_array }
  validates :max_rating, numericality: { only_integer: true }, inclusion: { in: ratings_array }
  validate :max_rating_greater_than_min_rating

  # scopes
  scope :alphabetical, -> { order('name') }
  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
  scope :for_rating, ->(rating) { where("min_rating <= ? and max_rating >= ?", rating, rating) }


  private
  def max_rating_greater_than_min_rating
    # only testing 'greater than' in this method, so...
    return true if self.max_rating.nil? || self.min_rating.nil?
    unless self.max_rating > self.min_rating
      errors.add(:max_rating, "must be greater than the minimum rating")
      return false
    end
    return true
  end

end

app/controllers/curriculums_controller.rb
class CurriculumsController < ApplicationController
	  # A callback to set up an @curriculum object to work with 
	before_action :set_curriculum, only: [:show, :edit, :update, :destroy]

	
	def index
		# get data on all curriculums and paginate the output to 10 per page
		@curriculums = Curriculum.active.alphabetical.paginate(page: params[:page]).per_page(10)
	end

	def show
		@camps = @curriculum.camps
	end

	def new
		@curriculum = Curriculum.new
	end

	def edit
	end

	def create
		@curriculum = Curriculum.new(curriculum_params)
		if @curriculum.save
			redirect_to @curriculum, notice: "#{@curriculum.name} was added to the system."
		else
			render action: 'new'
		end
	end

	def update
	  if @curriculum.update_attributes(curriculum_params)
	  	redirect_to @curriculum, notice: "#{@curriculum.name} was revised in the system."
	  else
	  	render action: 'edit'
	  end
	end

	def destroy
		@curriculum.destroy
		redirect_to curriculums_url, notice: "Removed #{@curriculum.name} from the system"
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_curriculum
			@curriculum = Curriculum.find(params[:id])
		end
		# Never trust parameters from the scary internet, only allow the white list through.
		def curriculum_params
			params.require(:curriculum).permit(:name, :description, :min_rating, :max_rating, :active)
		end

end

app/helpers/curriculums_helper.rb
module CurriculumsHelper
end

app/views/curriculums/_form.html.erb
<%= simple_form_for @curriculum, html: { class: 'form-horizontal' } do |f| %>
  <% if @curriculum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@curriculum.errors.count, "error") %> prohibited this Curriculum from being saved:</h2>

      <ul>
      <% @curriculum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
  <div class="field">
    <%= f.input :name%>
  </div>
  <div class="field">
    <%= f.input :description %>
  </div>
    <div class="field">
    <%= f.input :min_rating %>
  </div>
    <div class="field">
    <%= f.input :max_rating %>
  </div>
    <div class="field">
    <%= f.input :active, as: :radio_buttons %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </fieldset>
<% end %>

app/views/curriculums/edit.html.erb
<h1>Editing <%=@curriculum.name.titlecase%> Curriculum</h1>

<%= render 'form' %>

<%= link_to 'Show', @curriculum %> |
<%= link_to 'Back', curriculums_path %>

app/views/curriculums/index.html.erb
<h1>Curriculums Given at A&M Chess Camp</h1><br>

<table class="datagrid">
  <thead class="datagrid">
    <th>Name</th>
    <th>Ratings</th>
    <th>Times Used</th>
    <th>&nbsp;</th>
  </thead>
  <% for curriculum in @curriculums %>
    <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
      <td><%= link_to curriculum.name, curriculum_path(curriculum) %></td>
      <% if curriculum.min_rating==0 %>
      <td>Unrated - <%= curriculum.max_rating%></td>
      <% else %>
      <td><%= curriculum.min_rating %> - <%= curriculum.max_rating%></td>
      <% end %>
      <td><%= Camp.for_curriculum(curriculum).size%></td>
	  <td align="center">
			<%= link_to(raw('<button class="button">Edit</button>'), edit_curriculum_path(curriculum))  %>&nbsp;
	  </td>
    </tr>
  <% end %>
</table>
<p class="supertiny"></p>

<!-- Add the pagination using will_paginate gem -->
<span class="smtext">
<%= will_paginate @curriculums, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
</span>

<p><strong><%= link_to "Add A New Curriculum", new_curriculum_path %></strong></p>

app/views/curriculums/new.html.erb
<h1>New Curriculum</h1>

<%= render 'form' %>

<%= link_to 'Back', curriculums_path %>

app/views/curriculums/show.html.erb
<h2>Curriculum Details:</h2>

<p>
  <strong>Curriculum Name: </strong>
  <%= @curriculum.name.titlecase %> 
</p>

<p>
  <strong>Ratings: </strong>
  	<% if @curriculum.min_rating==0 %>
  	Unrated - <%= @curriculum.max_rating%>
  	<% else %>
  	<%= @curriculum.min_rating %> - <%= @curriculum.max_rating%>
  	<% end %>
</p>

<p>
  <strong>All about <%= @curriculum.name%>: </strong>
  <%= @curriculum.description %>
</p>

<% unless @camps.empty? %>
	<p>
	  <strong>When is this curriculum offered: </strong>
	  <% for camp in @camps %>
		<%= link_to camp.start_date.strftime("%B %e, %Y"), camp_path(camp) %>
		<% unless @camps.last.eql?(camp) %> | <% end %>
	  <% end %>
	</p>
<% end %>

<p>
	<strong>Is the camp active: </strong>
      <% if @curriculum.active==true %>
        Active
      <% else %>
        Inactive
      <% end %>
</p>

<p>
  <%= link_to "Edit", edit_curriculum_path(@curriculum) %> |
  <%= link_to "Destroy", @curriculum, confirm: 'Are you sure?', method: :delete %> |
  <%= link_to "View All", curriculums_path %>
</p>