config/routes.rb
ChessCampP2::Application.routes.draw do

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search
  
  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :camps
  resources :camp_instructors
  resources :instructors 
  resources :curriculums
  
  # You can have the root of your site routed with 'root'
  root 'home#index'

end

app/models/camp.rb
class Camp < ActiveRecord::Base
  # relationships
  belongs_to :curriculum
  has_many :camp_instructors
  has_many :instructors, through: :camp_instructors

  # validations
  validates_presence_of :curriculum_id, :time_slot, :start_date
  validates_numericality_of :cost, only_integer: true, greater_than_or_equal_to: 0
  validates_date :start_date, :on_or_after => lambda { Date.today }, :on_or_after_message => "cannot be in the past", :on => :create
  validates_date :end_date, :on_or_after => :start_date
  validates_inclusion_of :time_slot, in: %w[am pm], message: "is not an accepted time slot"
  validates_numericality_of :max_students, only_integer: true, greater_than: 0, allow_blank: true
  validate :curriculum_is_active_in_the_system
  validate :camp_is_not_a_duplicate, on: :create

  # scopes
  scope :alphabetical, -> { joins(:curriculum).order('name') }
  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
  scope :chronological, -> { order('start_date','end_date') }
  scope :morning, -> { where('time_slot = ?','am') }
  scope :afternoon, -> { where('time_slot = ?','pm') }
  scope :upcoming, -> { where('start_date >= ?', Date.today) }
  scope :past, -> { where('end_date < ?', Date.today) }
  scope :for_curriculum, ->(curriculum_id) { where("curriculum_id = ?", curriculum_id) }

  # instance methods
  def name
    self.curriculum.name
  end

  def already_exists?
    Camp.where(time_slot: self.time_slot, start_date: self.start_date).size == 1
  end

  # private
  def curriculum_is_active_in_the_system
    all_curric_ids = Curriculum.active.to_a.map(&:id)
    unless all_curric_ids.include?(self.curriculum_id)
      errors.add(:curriculum, "is not an active curriculum in the system")
    end
  end


  def camp_is_not_a_duplicate
    return true if self.time_slot.nil? || self.start_date.nil?
    if self.already_exists?
      errors.add(:time_slot, "already exists for start date and time slot")
    end
  end


end

app/controllers/camps_controller.rb
class CampsController < ApplicationController
	# A callback to set up an @camp object to work with 
	before_action :set_camp, only: [:show, :edit, :update, :destroy]

	def index
	  # get all camps in reverse chronological order, 10 per page
	  @camps = Camp.chronological.upcoming.paginate(page: params[:page]).per_page(10)
	end
	
	def show
	  # do this
	end
	
	def new
		@camp = Camp.new
	end
	
	def create
		@camp = Camp.new(camp_params)
		# @camp.instructor_ids.each do |a|
		# 	@camp_ins = CampInstructor.new(@camp.id, a)
		# 	@camp_ins.save
		# end
		if @camp.save
			flash[:notice] = "#{@camp.name} was added to the system."
			redirect_to @camp
		else
			render action: 'new'
		end
	end
	
	def edit
	end
	
	def update
		if @camp.update_attributes(camp_params)
			flash[:notice] = "#{@camp.name} was revised in the system."
			redirect_to @camp
		else
			render action: 'edit'
		end
	end
	
	def destroy
		@camp.destroy
		flash[:notice] = "#{@camp.name} was removed from the system"
		redirect_to camps_url
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_camp
			@camp = Camp.find(params[:id])
		end
		# Never trust parameters from the scary internet, only allow the white list through.
		def camp_params
			params.require(:camp).permit(:curriculum_id, :cost, :start_date, :end_date, :time_slot, :max_students, :active, :instructor_ids)
		end
end

app/helpers/camps_helper.rb
module CampsHelper
end

app/views/camps/_form.html.erb
<%= simple_form_for @camp, html: { class: 'form-horizontal' } do |f| %>
  <% if @camp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@camp.errors.count, "error") %> Prohibited this Camp from being saved:</h2>

      <ul>
      <% @camp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <fieldset>
  <div class="field">
    <%= f.input :curriculum_id, collection: Curriculum.active.alphabetical, prompt: "Select Curriculum Name" %>
  </div>
  <div class="field">
    <%= f.input :cost%>
  </div>
  <div class="field">
    <%= f.input :start_date, as: :date, order: [:month, :day, :year], include_blank: true %>
  </div>
  <div class="field">
    <%= f.input :end_date, as: :date, order: [:month, :day, :year], include_blank: true %>
  </div>
  <div class="field">
    <%= f.input :time_slot, :collection => [["Morning", "am"],["Afternoon", "pm"]] %>
  </div>
  <div class="field">
    <%= f.input :max_students%>
  </div>
  <div class="field">
    <%= f.input :active, as: :radio_buttons%>
  </div>
  <div class="field">
    <%= f.input :instructor_ids, label: "Instructor(s): ", collection: Instructor.active.alphabetical, as: :check_boxes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
 </fieldset>
<% end %>

app/views/camps/_instructors_checkboxes.html.erb
<p>
	<% for instructor in Instructor.active.alphabetical  %>
	   <%= check_box_tag "camp[instructor_ids][]", instructor.id, @camp.instructors.include?(instructor) %>
		 <%= instructor.name %>
	   <br />
	<% end  %>
</p>

app/views/camps/_list_of_instructors.html.erb
<p>
  <b><%= pluralize(@camp.instructors.size, 'Instructor') %></b><br />
  <ul>
    <% for instructor in @camp.instructors %>
      <li><%= link_to((instructor.name), instructor_path(instructor)) %></li>
    <% end  %>
  </ul>
</p>

app/views/camps/edit.html.erb
<h1>Editing <%=@camp.name.titlecase%> Camp</h1>

<%= render 'form' %>

<%= link_to 'Show', @camp %> |
<%= link_to 'Back', camps_path %>

app/views/camps/index.html.erb
<h1>Camps Given at A&M Chess Camp</h1><br>

<table class="datagrid">
  <thead class="datagrid">
    <th>Name</th>
    <th>Start Date</th>
    <th>End Date</th>
		<th>Cost</th> 
    <th>Time</th> 
    <th>&nbsp;</th>
  </thead>
  <% for camp in @camps %>
    <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
      <td><%= link_to camp.name, camp_path(camp) %></td>
      <td><%= camp.start_date.strftime("%m/%d/%y") %></td>
      <td><%= camp.end_date.strftime("%m/%d/%y") %></td>
      <td><%= camp.cost %></td>
      <td>
        <% if camp.time_slot=="am" %>
          Morning
        <% else %>
          Afternoon
        <% end %>
      </td>
	  <td align="center">
			<%= link_to(raw('<button class="button">Edit</button>'), edit_camp_path(camp))  %>&nbsp;
	  </td>
    </tr>
  <% end %>
</table>
<p class="supertiny"></p>

<!-- Add the pagination using will_paginate gem -->
<span class="smtext">
<%= will_paginate @camps, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
</span>

<p><strong><%= link_to "Add A New Camp", new_camp_path %></strong></p>

app/views/camps/new.html.erb
<h1>New Camp</h1>

<%= render 'form' %>

<%= link_to 'Back', camps_path %>

app/views/camps/show.html.erb
<h2><%=@camp.name%> Camp Details:</h2>

<p>
  <strong>Camp: </strong>
  <%= link_to @camp.name, curriculum_path(@camp.curriculum) %> 
</p>

<p>
  <strong>Cost: </strong>
  $<%= @camp.cost %>.00
</p>

<p>
  <strong>Date Period: </strong>
  <%= @camp.start_date.strftime("%m/%d/%y") %> - <%= @camp.end_date.strftime("%m/%d/%y") %> 
</p>

<p>
  <strong>Max Students: </strong>
  <%= @camp.max_students %> 
</p>

<p>
  <strong>Time Slot: </strong>
  <% if @camp.time_slot=="am" %>
    Morning
  <% else %>
    Afternoon
  <% end %>
</p>

<% unless @camp.instructors.empty? %>
  <p>
    <strong>Camp Instructors: </strong>
    <% for instructor in @camp.instructors %>
      <%= link_to instructor.name, instructor_path(instructor) %>
    <% unless @camp.instructors.last.eql?(instructor) %> | <% end %>
    <% end %>
  </p>
<% end %>

<p>
  <strong>Is the camp active: </strong>
      <% if @camp.active==true %>
        Active
      <% else %>
        Inactive
      <% end %>
</p>

<p>
  <%= link_to "Edit", edit_camp_path(@camp) %> |
  <%= link_to "Destroy", @camp, confirm: 'Are you sure?', method: :delete %> |
  <%= link_to "View All", camps_path %>
</p>