config/routes.rb
ChessCampP2::Application.routes.draw do

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search
  
  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :camps
  resources :camp_instructors
  resources :instructors 
  resources :curriculums
  
  # You can have the root of your site routed with 'root'
  root 'home#index'

end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  # relationships
  has_many :camp_instructors
  has_many :camps, through: :camp_instructors

  # validations
  validates_presence_of :first_name, :last_name, :phone
  validates_format_of :phone, :with => /\A(\d{10}|\(?\d{3}\)?[-. ]\d{3}[-.]\d{4})\z/, :message => "should be 10 digits (area code needed) and delimited with dashes only"
  validates_format_of :email, :with => /\A[\w]([^@\s,;]+)@(([\w-]+\.)+(com|edu|org|net|gov|mil|biz|info))\z/i, :message => "is not a valid format"

  # scopes
  scope :alphabetical, -> { order('last_name, first_name') }
  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
  scope :needs_bio, -> { where('bio IS NULL') }
  # scope :needs_bio, -> { where(bio: nil) }  # this also works...

  # class methods
  def self.for_camp(camp)
    # the 'instructive way'... (which I told you if you asked me for help)
    CampInstructor.where(camp_id: camp.id).map{ |ci| ci.instructor }
    # the easy way... 
    # camp.instructors
  end

  # instance methods
  before_save :reformat_phone

  def name
    last_name + ", " + first_name
  end
  
  def proper_name
    first_name + " " + last_name
  end

  private
  def reformat_phone
    # shorter, more direct way than in PATS
    self.phone = self.phone.to_s.gsub(/[^0-9]/,"")
  end
  
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
	# A callback to set up an @instructor object to work with 
	before_action :set_instructor, only: [:show, :edit, :update, :destroy]

	def index
		# finding all the active instructors and paginating that list (will_paginate)
		@instructors = Instructor.active.alphabetical.paginate(page: params[:page]).per_page(10)
	end

	def show
		
	end

	def new
		@instructor = Instructor.new
	end

	def edit
	end

	def create
		@instructor = Instructor.new(instructor_params)
		if @instructor.save
			# if saved to database
			flash[:notice] = "#{@instructor.proper_name} was added to the system."
			redirect_to @instructor # go to show instructor page
		else
			# return to the 'new' form
			render action: 'new'
		end
	end

	def update
		if @instructor.update_attributes(instructor_params)
			flash[:notice] = "#{@instructor.proper_name} was revised in the system."
			redirect_to @instructor
		else
			render action: 'edit'
		end
	end

	def destroy
		@instructor.destroy
		flash[:notice] = "Successfully removed #{@instructor.proper_name}"
		redirect_to instructors_url
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_instructor
			@instructor = Instructor.find(params[:id])
		end
		# Never trust parameters from the scary internet, only allow the white list through.
		def instructor_params
			params.require(:instructor).permit(:first_name, :last_name, :bio, :phone, :email, :active)
		end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<%= simple_form_for @instructor, html: { class: 'form-horizontal' } do |f| %>
  <% if @instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instructor.errors.count, "error") %> prohibited this  Instructor from being saved:</h2>

      <ul>
      <% @instructor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
  <div class="field">
    <%= f.input :first_name %>
  </div>
  <div class="field">
    <%= f.input :last_name %>
  </div>
  <div class="field">
    <%= f.input :bio %>
  </div>
  <div class="field">
    <%= f.input :email %>
  </div>
  <div class="field">
    <%= f.input :phone %>
  </div>
  <div class="field">
    <%= f.input :active, as: :radio_buttons %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</fieldset>
<% end %>

app/views/instructors/edit.html.erb
<h1>Editing <%=@instructor.proper_name.titlecase%> Instructor</h1>

<%= render 'form' %>

<%= link_to 'Show', @instructor %> |
<%= link_to 'Back', instructors_path %>

app/views/instructors/index.html.erb
<h1>Instructors at A&M Chess Camp</h1><br>

<table class="datagrid">
  <thead class="datagrid">
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th> 
    <th>Camps</th> 
    <th>&nbsp;</th>
  </thead>
  <% for instructor in @instructors %>
    <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
      <td><%= link_to instructor.name, instructor_path(instructor) %></td>
      <td><%= instructor.email %></td>
      <td>
          <%= "#{instructor.phone[0..2]}" %>-<%= "#{instructor.phone[3..5]}" %>-<%= "#{instructor.phone[6..9]}" %>
      </td>
      <% unless instructor.camps.empty? %>
        <td>
          <% for camp in instructor.camps %> 
            <%= link_to camp.name, camp_path(camp) %><br>
          <% end %>
        </td>
      <% end %>
      <% if instructor.camps.empty? %> <td> There are no camps for this instructor </td> <%end%>
	  <td align="center">
			<%= link_to(raw('<button class="button">Edit</button>'), edit_instructor_path(instructor))  %>&nbsp;
	  </td>
    </tr>
  <% end %>
</table>
<p class="supertiny"></p>

<!-- Add the pagination using will_paginate gem -->
<span class="smtext">
<%= will_paginate @instructors, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
</span>

<p><strong><%= link_to "Add A New Instructor", new_instructor_path %></strong></p>

app/views/instructors/new.html.erb
<h1>New Camp Instructor</h1>

<%= render 'form' %>

<%= link_to 'Back', instructors_path %>

app/views/instructors/show.html.erb
<h2>Camp Instructor Information:</h2>

<p>
  <strong>Instructor Name: </strong>
  <%= link_to @instructor.proper_name %> 
</p>
<p>
  <strong>Email: </strong>
  <%= @instructor.email %>
</p>
<p>
  <strong>Phone: </strong>
  <%= "#{@instructor.phone[0..2]}" %>-<%= "#{@instructor.phone[3..5]}" %>-<%= "#{@instructor.phone[6..9]}" %>
</p>
<p>
  <strong>Upcoming Camps: </strong>
  <% unless @instructor.camps.empty? %>
          <% for camp in @instructor.camps %> 
            <%= link_to camp.name, camp_path(camp) %>
            <% unless @instructor.camps.last.eql?(camp) %> | <% end %>
          <% end %>
      <% end %>
      <% if @instructor.camps.empty? %> There are no camps for this instructor <%end%>
</p>
<p>
  <strong>Is the camp active: </strong>
      <% if @instructor.active==true %>
      <td>Active</td>
      <% else %>
      <td>Inactive</td>
      <% end %>
</p>
<p>
  <strong>Instructor Details: </strong>
  <%= @instructor.bio %>
</p>

<p>
  <%= link_to "Edit", edit_instructor_path(@instructor) %> |
  <%= link_to "Destroy", @instructor, confirm: 'Are you sure?', method: :delete %> |
  <%= link_to "View All", instructors_path %>
</p>