config/routes.rb
ChessCampP2::Application.routes.draw do

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search
  
  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :camps
  resources :camp_instructors
  resources :instructors 
  resources :curriculums
  
  # You can have the root of your site routed with 'root'
  root 'home#index'

end

app/models/camp_instructor.rb
class CampInstructor < ActiveRecord::Base
  # relationships
  belongs_to :camp
  belongs_to :instructor

  # validations
  validates :camp_id, presence: true, numericality: { greater_than: 0, only_integer: true }
  validates :instructor_id, presence: true, numericality: { greater_than: 0, only_integer: true }
  validate :instructor_is_not_already_assigned_to_camp
  validate :instructor_is_active_in_system
  validate :camp_is_active_in_system

  private
  def instructor_is_not_already_assigned_to_camp
    unless CampInstructor.where(camp_id: self.camp_id, instructor_id: self.instructor_id).to_a.empty?
      errors.add(:instructor, "has already been assigned to this camp")
    end
  end

  def instructor_is_active_in_system
    all_instructors_ids = Instructor.active.to_a.map(&:id)
    unless all_instructors_ids.include?(self.instructor_id)
      errors.add(:instructor, "is not an active instructor in the system")
    end
  end

  def camp_is_active_in_system
    all_camps_ids = Camp.active.to_a.map(&:id)
    unless all_camps_ids.include?(self.camp_id)
      errors.add(:camp, "is not an active camp in the system")
    end   
  end
end

app/controllers/camp_instructors_controller.rb
class CampInstructorsController < ApplicationController

	# A callback to set up an @camp_instructor object to work with 
	before_action :set_camp_instructor, only: [:show, :edit, :update, :destroy]

	def index
		# get all the data on camp_instructors in the system, 10 per page
		@camp_instructors = CampInstructor.paginate(page: params[:page]).per_page(10)
	end

	def show
		# do this
	end

	def new
		@camp_instructor = CampInstructor.new
	end

	def edit

	end

	def create
		@camp_instructor = CampInstructor.new(camp_instructor_params)
		if @camp_instructor.save
			flash[:notice] = "Successfully created Camp Instructor."
			redirect_to @camp_instructor
		else
			render action: 'new'
		end
	end

	def update
		if @camp_instructor.update_attributes(camp_instructor_params)
			flash[:notice] = "Successfully updated Camp Instructor."
			redirect_to @camp_instructor
		else
			render action: 'edit'
		end
	end

	def destroy
		@camp_instructor.destroy
		flash[:notice] = "Successfully destroyed Camp Instructor."
		redirect_to camp_instructors_url
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_camp_instructor
			@camp_instructor = CampInstructor.find(params[:id])
		end
		# Never trust parameters from the scary internet, only allow the white list through.
		def camp_instructor_params
			params.require(:camp_instructor).permit(:camp_id, :instructor_id)
		end
end

app/helpers/camp_instructors_helper.rb
module CampInstructorsHelper
end

app/views/camp_instructors/_form.html.erb
<%= simple_form_for @camp_instructor, html: { class: 'form-horizontal' } do |f| %>
  <% if @camp_instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@camp_instructor.errors.count, "error") %> prohibited this Camp Instructor from being saved:</h2>

      <ul>
      <% @camp_instructor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :camp_id, label: "Camp: ", collection: Camp.active.alphabetical, as: :radio_buttons %>
  </div>
  <div class="field">
    <%= f.input :instructor_id, label: "Instructor: ", collection: Instructor.active.alphabetical, as: :radio_buttons%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/camp_instructors/edit.html.erb
<h1>Editing Camp Instructor</h1>

<%= render 'form' %>

<%= link_to 'Show', @camp_instructor %> |
<%= link_to 'Back', camp_instructors_path %>

app/views/camp_instructors/index.html.erb
<h1>Camp Instructors Given at A&M Chess Camp</h1><br>

<table class="datagrid">
  <thead class="datagrid">
    <th>ID</th>
    <th>Camp</th>
    <th>Camp Start Date</th>
    <th>Camp End Date</th>
		<th>Instructors</th> 
    <th>&nbsp;</th>
  </thead>
  <% for camp_instructor in @camp_instructors %>
    <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
      <td><%= link_to camp_instructor.id, camp_instructor_path(camp_instructor) %></td>
      <td><%= link_to camp_instructor.camp.name, camp_path(camp_instructor.camp) %></td>
      <td><%= camp_instructor.camp.start_date.strftime("%m/%d/%y") %></td>
      <td><%= camp_instructor.camp.end_date.strftime("%m/%d/%y") %></td>
      <td><%= link_to camp_instructor.instructor.name, instructor_path(camp_instructor.instructor) %></td>
	  <td align="center">
			<%= link_to(image_tag("icons/edit_dg.gif", border: 0), edit_camp_instructor_path(camp_instructor))  %>&nbsp;
	  </td>
    </tr>
  <% end %>
</table>
<p class="supertiny"></p>

<!-- Add the pagination using will_paginate gem -->
<span class="smtext">
<%= will_paginate @camp_instructors, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
</span>

<p><strong><%= link_to "Add A New Camp Instructor", new_camp_instructor_path %></strong></p>

app/views/camp_instructors/new.html.erb
<h1>New Camp Instructor</h1>

<%= render 'form' %>

<%= link_to 'Back', camp_instructors_path %>

app/views/camp_instructors/show.html.erb
<h2>Camp Instructor Information:</h2>

<p>
  <strong>Camp:</strong>
  <%= link_to @camp_instructor.camp.name, camp_path(@camp_instructor.camp) %> 
</p>
<p>
  <strong>Instructor:</strong>
  <%= link_to @camp_instructor.instructor.name, instructor_path(@camp_instructor.instructor) %>
</p>

<p>
  <%= link_to "Edit", edit_camp_instructor_path(@camp_instructor) %> |
  <%= link_to "Destroy", @camp_instructor, confirm: 'Are you sure?', method: :delete %> |
  <%= link_to "View All", camp_instructors_path %>
</p>